# Matrix Algebra

This notebook aims to cover the basics of all matrix algebra needed for a full understanding of multivariate analysis methods using Python + Numpy.

In [1]:
import numpy as np

## Notation and Definitions

### Matrices, Vectors and Scalars

A matrix is an arrangment of numbers or variables into rows and columns in written text such as this, **boldface** is used to represent a matrix whereas in handwritten text it might be common to write with $\bar{\mathrm{overline}}$ or even double $\bar{\bar{\mathrm{overline}}}$. A vector is a matrix with only a single row or column and a scalar is a single number or a matrix with only one row and one column.

$$
{\bf A} = \begin{pmatrix}4 & 8\\ 15 & 16\\ 23 & 42\end{pmatrix} = \begin{pmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\\a_{31}&a_{32}\end{pmatrix}=(a_{ij})
$$

Let's take some examples,
$$
{\bf A} = \begin{pmatrix}4 & 2 & 3 \\ 7 & 5 & 8\end{pmatrix} \ \mathrm{and}\ \ {\bf B} = \begin{pmatrix}3 & -2 & 4 \\ 6 & 9 & -5\end{pmatrix}
$$

Before we look at operations, first we need to define the matrices:

In [2]:
A = np.array([(4,2,3),(7,5,8)])
B = np.array([(3,-2,4),(6,9,-5)])

### Matrix Opperations

Matrices can be added and subtracted.

**A+B**

In [3]:
A+B

array([[ 7,  0,  7],
       [13, 14,  3]])

In [4]:
A-B

array([[ 1,  4, -1],
       [ 1, -4, 13]])

As can be seen, when adding or subtracting matrices this is done element wise and then only if the dimensions of the matrices are the same. 

The transpose of a matrix is denoted with an appostrophe such as **A'** this is the operation of changing the rows and columns of the matrix.
$$
{\bf A} = \begin{pmatrix}4 & 2 & 3 \\ 7 & 5 & 8\end{pmatrix} \ \ \ \ {\bf A'} = \begin{pmatrix}4 & 7\\ 2 & 5 \\ 3 & 8\end{pmatrix}
$$

When multiplying matrices ${\bf AB}\neq {\bf BA}$ as the operations can only be done when the number of columns in the first matrix equals the number of rows in the second. The resulting matrix will be a square matrix of this dimension. As each element can be defined as:

$$
{\bf C} = {\bf AB}\ \ \ \mathrm{where}\ \ \ c_{ij}=\sum_k a_{ik}b_{kj}
$$
i.e. $c_{ij}$ is the sum of the products of the $i$th row of **A** and the $j$th column of **B**

This is done for us in Numpy so, let's try some examples also including the transpose.

**A'A**

In [5]:
np.dot(A.T,A)

array([[65, 43, 68],
       [43, 29, 46],
       [68, 46, 73]])

**AA'**

In [6]:
np.dot(A,A.T)

array([[ 29,  62],
       [ 62, 138]])

Matrices have some fun properties. Whilst matrix multiplication is non-commutative ($\bf AB\neq BA$) addition and subtraction are. e.g.

In [7]:
B+A

array([[ 7,  0,  7],
       [13, 14,  3]])

further more the transpose of the sum (or differece) of two matrices is the same as the sum (or difference) of those matrices transposed:
$$
({\bf A}+{\bf B})'={\bf A'}+{\bf B'}
$$

In [8]:
(A+B).T

array([[ 7, 13],
       [ 0, 14],
       [ 7,  3]])

In [9]:
A.T+B.T

array([[ 7, 13],
       [ 0, 14],
       [ 7,  3]])

by taking the transpose twice you get back to the orriginal matrix

In [10]:
A.T.T

array([[4, 2, 3],
       [7, 5, 8]])

### Determinant

The determinant of a square $n\times n$ matrix is the sum of all $n!$ possible products of $n$ elements according to some rules. For a two by two matrix 
$$
|{\bf A}|=\begin{vmatrix}a_{11}&a_{12}\\a_{21}&a_{22}\end{vmatrix}=a_{11}a_{22}-a_{21}a_{12}
$$
and for a three by three:
$$
|{\bf A}|=\begin{vmatrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\end{vmatrix}$$
$$
=a_{11}a_{22}a_{33}+a_{12}a_{23}a_{31}+a_{13}a_{32}a_{21}-a_{31}a_{22}a_{13}+a_{32}a_{23}a_{11}+a_{33}a_{12}a_{21}
$$

I remember it as all backward diagonals minus all forward diagonals.

Do do some examples we need some square matrices.
$$
{\bf A}=\begin{pmatrix}1 & 3\\2 & -1\end{pmatrix}\ \ \ {\bf B}=\begin{pmatrix}2 & 0 \\ 1 & 5\end{pmatrix}
$$


In [11]:
A = np.array([(1,3),(2,-1)])
B = np.array([(2,0),(1,5)])

**AB**$\neq$**BA**

In [12]:
np.dot(A,B)

array([[ 5, 15],
       [ 3, -5]])

In [13]:
np.dot(B,A)

array([[ 2,  6],
       [11, -2]])

but the determinants do hold. i.e. |**AB**|=|**A**||**B**|

In [14]:
np.linalg.det(np.dot(A,B))

-70.000000000000028

In [15]:
np.linalg.det(A)*np.linalg.det(B)

-70.0

### Trace

The trace is the sum of all the diagonal elements of a square matrix. 

$$
\mathrm{tr}({\bf A})=\sum_{i=j}^na_{ij}
$$

This is important because tr(**AB**)=tr(**BA**) whilst also tr(**A** + **B**) = tr(**A**)+tr(**B**)

In [16]:
A+B

array([[3, 3],
       [3, 4]])

In [17]:
np.trace(A+B)

7

In [18]:
np.trace(A)+np.trace(B)

7

### Special Matrices

A matrix is diagonal if it is equal to it's transpose.

The diagonal of a square matrix is just the elements $i=j$ that we just summed for the trace and zeros everywhere else. 

In [19]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
np.diag(A)

array([1, 5, 9])

a diagonal matrix containing only ones called the identity matrix.

In [20]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Inverse
The inverse of a matrix is defined as that which when multiplied by the matrix gives the indentity matrix.
$$
{\bf AA}^{-1}={\bf A}^{-1}{\bf A}={\bf I}
$$

There are several different ways to calculate this but numpy has them included.

In [21]:
A = np.array([(2,-1),(-1,2)])

In [22]:
AI = np.linalg.inv(A)

In [23]:
np.dot(A,AI)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [24]:
A = np.mat([(2,-1),(-1,2)])
np.dot(A,A.I)

matrix([[ 1.,  0.],
        [ 0.,  1.]])

## More?

Other topics not yet discussed here that will be added if addressed in later chapters:
* rank
* decomposition
* eigenvalues

More information on the range of matrix algebra can be found on the [datacamp Linear Algebra CheatSheet](https://www.datacamp.com/community/blog/python-scipy-cheat-sheet#gs.A4CwjIE).